alias egrep='gegrep --color=auto'
alias fgrep='gfgrep --color=auto'
alias grep='ggrep --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='gls --color=auto'

alias cd..='cd ..'
#alias c='clear'
#alias e='exit'
alias ..='cd ..'

alias notepad='open -a TextEdit --args $argv'
alias config_profile='code ~/.bash_profile'
